#################
# FtpAutoBackup #
#################

#############################
# 改名为 config.ini 即可生效 #
#############################


# ============================ FTP部分 ============================================

[Ftp-Login] # FTP 登录配置项

# 匿名登陆，默认禁用，如果使用联机插件请不要启用，存在安全风险！，0关闭，1开启
anon = 0

# 如果禁用匿名登陆，则必须设置用户名和密码
# user = 用户名，pass = 登陆密码
user = 192.168.50.176
pass = 180846


[Ftp-Network] # FTP 网络配置项

# 传输端口, 可以使用5000（小于1024）, 和其他sftp工具统一
port = 21

# 会话关闭前的超时时间（秒），0关闭超时，建议设置20
timeout = 20


[Ftp-Basic Settings] # FTP 其他配置项

# 显示所有可用挂载点，0关闭，1开启
mount_devices = 1

# 存档写入权限, 默认关闭, 避免误操作，需要 mount_devices = 1
save_writable = 0

# 允许挂载bis分区(小心BAN机)，需要 mount_devices = 1，0关闭，1开启
# 此功能无效，已阉割
mount_bis = 0

# 传输时候手柄上的HOME键闪烁
led = 0

# 使用本地时区而不是GMT（UTC）时区
use_localtime = 0


[Ftp-Custom Mount Point] # FTP 自定义挂载点配置项

# 自定义挂载点，需要 mount_devices = 1
; custom_name1 = 这是挂载点名字
; custom_path1 = 这是要挂载的路径

; custom_name2 = 这是挂载点名字
; custom_path2 = /switch

# 最多10个自定义挂载点，要按顺序添加1-10
; custom_name10 = 这是挂载点名字
; custom_path10 = /config


# ============================ FTP部分结束 ============================================

# ============================ 自动备份部分 ============================================


[ ] # 自动备份配置项

# 启用自动备份功能，0关闭，1开启
auto_backup_enabled = 1

# 最大备份数量
maxback = 5




[Backup-WebDAV] # WebDAV 配置

# 启用自动上传功能，0关闭，1开启，需要auto_backup开启
WebDAV_enabled = 0
origin = https://dav.jianguoyun.com
basepath = dav
username = 2428911987@qq.com
password = at5p7b8kjdcrzuwv



# ============================ 自动备份部分结束 ============================================

# ============================ 通用配置项 ============================================


[Common] # 通用配置项

# 启用日志输出到 /config/ftpsrv/log.txt，0关闭，1开启
log = 0

# 不使用下划线替换非ASCII字符，0关闭，1开启
skip_ascii_convert = 1

# ============================ 通用配置项结束 ============================================