##########
# ftpsrv #
##########

#######################################################################
# Rename config.ini.template to config.ini for changes to take effect.#
#######################################################################

[Login]
# disabled by default, do not enable if using ldn_mitm as
# it's a security risk - you have been warned!
# 1: 开启
# 0: 关闭
# 匿名登陆
anon = 1

# if anon is disabled, then user and pass must be set.
# 不使用匿名登陆的时候, 需要把前面的分号删掉, 并填写好
# user = 用户名
# pass = 登陆密码
user = 1
pass = 1

[Network]
# ports to be opened (< 1024), however, port 21 works fine for me...
# 传输端口, 可以使用5000, 和其他sftp工具统一.
port = 21

# timeout in seconds until a session is closed.
# if 0, then no timeout is set.
# it is recommended to set this to an actual value, eg 20.
# 0: 关闭
# 其他数值是设置自动超时关闭的时间, 单位是秒
timeout = 0

[Misc]
# use local time zone over gm (UTC) time zone.
# 使用本地时间
use_localtime = 0

[Log]
# enables log output to /config/ftpsrv/log.txt
# 1: 开启
# 0: 关闭
# 调试日志, 会在本地生成日志文件, 默认关闭
log = 1

# options specific to Nintendo Switch
[Nx]
# enables showing all available mount points at root "/"
# for example, SdCard is as at "/sdmc:"
# 1: 开启
# 0: 关闭
# 根目录挂载所有可挂载的路径
mount_devices = 0

# allows save data to be writable, needs mount_devices = 1
# 1: 开启
# 0: 关闭
# 存档写入权限, 默认关闭, 避免误操作
save_writable = 1

# allows for bis partitions to be mounted, needs mount_devices = 1
# WARNING: modifying bis files can soft brick your switch!
# 1: 开启
# 0: 关闭
# 开启bis文件挂载
mount_bis = 0

# uncomment to override the port for application
# 应用程序端口, 覆盖默认端口设置
# app_port = 21

# uncomment to override the port for sysmode
# 系统后台模块端口, 覆盖默认端口设置
# sys_port = 21

# enables led on the controller to light flash
# 1: 开启
# 0: 关闭
# 传输时候手柄上的HOME键闪烁
led = 0

# options specific to Nintendo Switch App
# 指定自制应用的设置
[Nx-App]
; anon = 0
; user = ""
; pass = ""
; port = 21
; timeout = 0
; use_localtime = 0
; log = 0
; mount_devices = 0
; save_writable = 0
; mount_bis = 0
; led = 0

# options specific to Nintendo Switch Sysmodule
# 指定系统模块的设置
[Nx-Sys]
; anon = 0
; user = ""
; pass = ""
; port = 21
; timeout = 0
; use_localtime = 0
; log = 0
; mount_devices = 0
; save_writable = 0
; mount_bis = 0
; led = 0

[Backup]
maxback = 5

[WebDAV]
enabled = 1
origin = https://dav.jianguoyun.com
basepath = dav
username = 
password = 
