##############
# AutoBackup #
##############

#############################
# 改名为 config.ini 即可生效 #
#############################

[Login]
# 默认禁用，如果使用联机插件请不要启用，存在安全风险！
# 1: 开启
# 0: 关闭
# 匿名登陆
anon = 0

# 如果禁用匿名登陆，则必须设置用户名和密码
# 不使用匿名登陆的时候, 需要把前面的分号删掉, 并填写好
# user = 用户名
# pass = 登陆密码
user = 192.168.50.176
pass = 180846

[Network]
# 传输端口, 可以使用5000（小于1024）, 和其他sftp工具统一
port = 21

# 会话关闭前的超时时间（秒）
# 如果为0，则不设置超时
# 建议设置为实际值，例如20
timeout = 20

[Misc]
# 使用本地时区而不是GMT（UTC）时区
use_localtime = 0

[Log]
# 启用日志输出到 /config/ftpsrv/log.txt
# 1: 开启
# 0: 关闭
log = 0

# Nintendo Switch 专用选项
[Nx]
# 在根目录"/"显示所有可用挂载点
# 例如，SdCard位于"/sdmc:"
# 1: 开启
# 0: 关闭
# 根目录挂载所有可挂载的路径
mount_devices = 1

# 允许存档数据可写，需要 mount_devices = 1
# 1: 开启
# 0: 关闭
# 存档写入权限, 默认关闭, 避免误操作
save_writable = 0

# 允许挂载bis分区，需要 mount_devices = 1
# 警告：修改bis文件可能导致Switch软砖！
# 1: 开启
# 0: 关闭
# 开启bis文件挂载
mount_bis = 0

# 启用手柄LED灯闪烁
# 1: 开启
# 0: 关闭
# 传输时候手柄上的HOME键闪烁
led = 0

# 不使用下划线替换非ASCII字符，0关闭，1开启
skip_ascii_convert = 1

# Nintendo Switch 系统模块专用选项
# 统一的配置项，可以不管
[Nx-Sys]
; anon = 0
; user = ""
; pass = ""
; port = 21
; timeout = 0
; use_localtime = 0
; log = 0
; mount_devices = 0
; save_writable = 0
; mount_bis = 0
; led = 0

# 最大备份数量
[Backup]
maxback = 5

# WebDAV 配置
[WebDAV]
enabled = 0
origin = https://dav.jianguoyun.com
basepath = dav
username = 2428911987@qq.com
password = at5p7b8kjdcrzuwv
